In [356]:
import pandas as pd
df = pd.read_csv("mand_kor_processed_latest.csv")
df = df.drop(df.index[62])
df.head()

,Unnamed: 0,Column1,Column2,mand_pron,mand_tone,Column4,Column5,Column6,Column7,Column8,Column9,Column10,Column11,kor_0,kor_1,kor_2
0,0,犬,598.0,quan,3.0,hyun2,khién,NaN,ián,2qyoe,けん,けん,けん,ㄱ,ㅕ,ㄴ
1,1,馬,599.0,ma,3.0,maa5,mâ,ma1,NaN,3mo,め,め,ば,ㅁ,ㅏ,NaN
2,2,西,603.0,xi,1.0,sai1,sî,xi1,sai,1xi,さい,さい,せい,ㅅ,ㅓ,NaN
3,3,車,604.0,che,1.0,ce1,chhâ,ca1,chhia,1tsho,しゃ,しゃ,しゃ,ㅊ,ㅏ,NaN
4,4,酉,650.0,you,3.0,jau5,yu,NaN,iú,NaN,ゆ,ゆ,ゆう,ㅇ,ㅠ,NaN

In [357]:
initials = ["ng", "gw", "kw", "b", "p", "m", "f", "d", "t", "l", "g", "k", "n", "h", "w", "z", "c", "s", "j"]
finals = ["aa", "aai", "aau", "aam", "aan", "aang", "aap", "aat", "aak", "ai", "au", "am", "an", \
          "ang", "ap", "at", "ak", "e", "ei", "eu", "em", "eng", "ep", "ek", "i", "iu", "im", "in", \
          "ing", "ip", "it", "ik", "o", "oi", "ou", "on", "ong", "ot", "ok", "u", "ui", "un", "ung", \
          "ut", "uk", "oe", "eoi", "eon", "oeng", "eot", "oek", "yu", "yun", "yut", "m", "ng"]
coda = ['p', 't', 'k', 'm', 'n', 'ng']

In [358]:
def cantonizer(srt):
    if type(srt) == float:
        return ('','','','')
    tone = srt[-1]
    s = srt[:-1]
    l = ['','','', tone]
    for i in initials:
        if s.startswith(i):
            l[0] = i
            s = s[len(i):]
            break
    for i in finals:
        if s == i:
            l[1] = i
            break
    for i in coda:
        if l[1].endswith(i):
            l[1] = l[1][:-len(i)]
            l[2] = i
    if (l[0] == 'm' or l[0] == 'ng') and not l[1]:
        l[1] = l[0]
        l[0] = ''
#     print(l)
    assert(l[0] + l[1] + l[2] + l[3] == srt)
    assert(l[1] != '')
    assert(l[0] in initials or l[0] is '')
    assert(l[2] in coda or l[2] is '')
    return l

In [359]:
li = df['Column4'].tolist()

In [360]:
for i in range(len(li)):
    try:
        li[i] = cantonizer(li[i])
    except:
        print("Error: " + str(li[i]))
        li[i] = ('','','','')

Error: keui4
Error: leui6
Error: pet6
Error: nga4
Error: yeung4
Error: seung1
Error: jeuk3
Error: zeuk3
Error: wa1
Error: ching1
Error: keui4
Error: chi4
Error: cho2
Error: keui4
Error: only
Error: zeun2
Error: jeuk6
Error: chung4
Error: chyut3
Error: yuk6
Error: ja1

In [361]:
j1, j2, j3, j4 = zip(*li)
df = df.drop(df.columns[[5]], axis = 1)

In [362]:
df.insert(loc=5, column='canto_tone', value=j4)
df.insert(loc=5, column='canto_coda', value=j3)
df.insert(loc=5, column='canto_nucl', value=j2)
df.insert(loc=5, column='canto_onset', value=j1)
df.head()

,Unnamed: 0,Column1,Column2,mand_pron,mand_tone,canto_onset,canto_nucl,canto_coda,canto_tone,Column5,Column6,Column7,Column8,Column9,Column10,Column11,kor_0,kor_1,kor_2
0,0,犬,598.0,quan,3.0,h,yu,n,2,khién,NaN,ián,2qyoe,けん,けん,けん,ㄱ,ㅕ,ㄴ
1,1,馬,599.0,ma,3.0,m,aa,,5,mâ,ma1,NaN,3mo,め,め,ば,ㅁ,ㅏ,NaN
2,2,西,603.0,xi,1.0,s,ai,,1,sî,xi1,sai,1xi,さい,さい,せい,ㅅ,ㅓ,NaN
3,3,車,604.0,che,1.0,c,e,,1,chhâ,ca1,chhia,1tsho,しゃ,しゃ,しゃ,ㅊ,ㅏ,NaN
4,4,酉,650.0,you,3.0,j,au,,5,yu,NaN,iú,NaN,ゆ,ゆ,ゆう,ㅇ,ㅠ,NaN

In [363]:
initials = ['b', 'p', 'm', 'f', 'd', 't', 'n', 'l', 'g', 'k', 'h', 'j', 'q' \
           ,'x', 'zh', 'ch', 'sh', 'r', 'z', 'c', 's']
finals = ['i', 'e', 'a', 'ei', 'ai', 'ou', 'ao', 'en', 'an', 'ong', 'eng', 'ang' \
          ,'yi', 'ye', 'ya', 'ie', 'ia', 'you', 'iu', 'yao', 'iao', 'yin', 'in', 'yan', 'ian', \
          'yong', 'iong', 'ying', 'ing', 'yang', 'iang', 'wu', 'u', 'wo', 'uo', 'o', 'wa', 'ua', \
          'wei', 'ui', 'wai', 'uai', 'wen', 'un', 'wan', 'uan', 'weng', 'wang', 'uang',\
          'yu', 'ü', 'yue', 'üe', 'ue', 'yun', 'ün', 'üan', 'yuan']
coda = ['n', 'ng']

In [364]:
def mandar(srt):
    if type(srt) == float:
        return ('','','')
    s = srt
    s = s.lower()
    if s == 'er':
        return ('', 'er', '')
    l = ['','','']
    for i in initials:
        if s.startswith(i):
            l[0] = i
            s = s[len(i):]
            break
    for i in finals:
        if s == i:
            l[1] = i
            break
    for i in coda:
        if l[1].endswith(i):
            l[1] = l[1][:-len(i)]
            l[2] = i
    assert(l[0] + l[1] + l[2] == srt.lower())
    assert(l[1] != '')
    assert(l[0] in initials or l[0] is '')
    assert(l[2] in coda or l[2] is '')
    return l

In [365]:
li = df['mand_pron'].tolist()

In [366]:
for i in range(len(li)):
    try:
        li[i] = mandar(li[i])
    except:
        print("Error: " + str(li[i]))
        li[i] = ('','','')

Error: ḿ
Error: ê̄
Error: tū'ao
Error: jiejue
Error: shangxia
Error: jisì
Error: pànbie
Error: yúpiao
Error: xiandàng
Error: Kunlún
Error: jiǔzhi
Error: nǚnu

In [ ]:
j1, j2, j3 = zip(*li)
df = df.drop(df.columns[[4]], axis = 1)

In [ ]:
df.insert(loc=4, column='mando_coda', value=j3)
df.insert(loc=4, column='mando_nucl', value=j2)
df.insert(loc=4, column='mando_onset', value=j1)
df = df.drop(df.columns[[0]], axis = 1)
df.head()

In [ ]:
df.to_csv("mand_cant_kor_all_processed.csv", encoding="utf-8", index=True)